[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
fs_permissions = [{ access = "read-write", path = "./"}]

[dependencies]
forge-std = "1.9.6"
"@openzeppelin-contracts" = "5.3.0"
solady = "0.1.16"

etherscan_api_key = "KWQ7H2N2HNPEX3JU7WWKGIIKGYWE1M118N"

[rpc_endpoints]
base = "https://8453.rpc.thirdweb.com/{THIRDWEB_KEY}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
