[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
fs_permissions = [{ access = "read-write", path = "./"}]

[dependencies]
forge-std = "1.9.6"
"@openzeppelin-contracts" = "5.3.0"
solady = "0.1.16"

[rpc_endpoints]
base = "https://8453.rpc.thirdweb.com/Rb2VlJbNi3XVy5uzPVee0ow-pGFqG4XGaagK4dP0bsVhdqKAS6e7iRNRYi1-Bew9PRmP1Ni_lU5drxOLPqgtLQ"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
